[preface]
= Introduction to Nordic Smart Government & Business (NSG&B)

This {nsg} BIS provides the specification for implementing eReceipt. The format is based on Peppol Invoice as part of Peppol BIS Billing 3.0 but is adapted to meet functional requirements for the exchange of credit-card transactions and other invoice attachments. The format will be developed for use in a nordic pilot before a later decision on ownership and government. Possible options in the future are
* eReceipt remains a NSG&B format
* The format is converted to a Peppol BIS
* The format is managed by CEN

The vision of NSG is to create value for the SMEs by making real time business data accessible and usable for innovation and growth across the region, in an automatic, consent based and secure manner.
Our core idea is that structured and standardized business data can be shared automatically and thereby replace burdensome manual handling of data exchange. This involves alignment of digital systems and services as opposed to digital silos and requires collaboration across sectors using the business data.

The mission is thus not to implement a centralized IT system, but to enable and facilitate a transformation of the Nordic ecosystem and business processes, both nationally and across the Nordic borders. We in the public sector cannot - and do not want to - create the Nordic region's digital and transparent ecosystems for financial information by ourselves.
We are dependent on actors in the private market and are convinced that the best solutions will come when we co-create. This of course opens up new business opportunities for actors in the private market.
Though, we need to emphasize that co-creation does not give any exclusive rights or access to information. NSG is a transparent collaborative project run by government agencies but in collaboration and knowledge sharing with a larger community of stakeholders. But of course, the closer you are to the development, the more input we get together.

For more information about NSG see: http://www.nordicsmartgovernment.org


== Document Structure

This document is structured as follows:

*	*Chapters 1 - 5* gives general information on the business processes, requirements and functionalities
*	*Chapter 6* describes the semantical data types
*	*Chapters 7 - 9* describes VAT, calculations and rounding.
*	*Chapter 10* provides examples of selected parts of the invoice
*	*Chapter 11* gives details and links to all code lists used
* *Chapter 12* gives information on Peppol identifiers
*	*Chapter 13* describes in detail central information elements.
*	*Chapters 14 and 15* provides information on validation and validation rules
*	*Annexes* give information on restrictions according to {EN16931}, use of Cross Industry Invoice syntax and national and syntax rules.

== Scope

This document provides the detailed specification for the use and exchange of the eReceipt transaction. 

== Audience

The audience for this document are organizations wishing to be NSG enabled for exchanging eReceipt transactions, and/or their ICT-suppliers. These organizations may be:

     * Service providers
     * Contracting Authorities (CA)
     * Economic Operators (EO)
     * Software Developers

More specifically, roles addressed are the following:

    * ICT Architects
    * ICT Developers
    * Business Experts
